server:
  port: 8091
spring.jpa.show-sql: true
#spring.jpa.hibernate.ddl-auto: create
spring:
  flyway:
    locations:
      - classpath:db/migration
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/mydb2
    username: jerry2
    password: "my1"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
